title: "Vash's website"
description: "My Blog"
baseurl: ""        # Leave empty for GitHub Pages user/organization sites
url: "https://vhungerford.github.io"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author info (optional)
author:
  name: "Vash Hungerford"
  email: "vashhungerford@gmail.com"

# Permalinks (optional)
permalink: /:year/:month/:day/:title/

# Collections (optional)
collections:
  posts:
    output: true

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
